language: go
go:
- 1.12.x
env:
- GO111MODULE=on GOOS=linux GOARCH=amd64
matrix:
  allow_failures:
  - go: tip
  fast_finish: true
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: bhavikkumar-github
    token:
      secure: c5v4OvSRZ7D5z00vE03z/ZvmB7jgf0GZUdRs7C4YZdW1CgxtQkg7pOdIxNO2P01n+awxXFQLgdNQYiLtoJzmGFDVdq+Jdxfp5eplnXMN3M8PC3TwuvZJRdQU3w6ar0dW2sfJAgq3WgCPbfN/9S27vsZaYUSsREox6mVJi4PiKUw4U2P767w8SolpfE6NV3MUnbzdLAtVgV5nn/4Q22T5BAEp6bM6gvPfJdPhfCYqKFysTf/ViZiWP5jfud2rbmmn+Ply7uZ5auoyj2t/nAQiK1uIr8qzvk7A2PRw5HggEgSGMIjTqGzG5ie0tSMr9INdAEUsVNDuVdGNq2/yUR+FQVDyJqbsPIhhwDIiUDncgXPZ/3F7e+2ySqbSR7ljfhjroIjj62Gwq8lBZvQYjURvZUmR6Td0YaHWo1mXg4eYOV39ndI1okYRpEForTbweZ+JVTE7IJQmRFJHiXW7BUXr1Joxd4KCvxtwxwhsqXqvg1fn8smtx5QI2d509HehnUA0BHMvzEXlBqPoT4l9H4AjCYJ38SjJIuzgQXfjeA98gICA5wPpfipG0RDSUgiQavPpst8AzhIUTlwTLehf7cd4NhvkDejOyPAZMNLi0yHhxEwoEU7kYU6fiyfBLvIv8FqkZSbakRDdXJlBPGKYl8OCvcR6YPIJ+gTTvLva0QGuORA=
install:
- go mod download
- go build -ldflags="-s -w" -o main main.go
script:
- go vet ./... 2> govet-report.out
- go test ./... -coverprofile=coverage.out -json > report.json
after_success:
- sonar-scanner
- mkdir build
- zip build/cloudwatch-log-destination$TRAVIS_TAG.zip main
deploy:
  provider: releases
  api_key:
    secure: fiqhQ8z2ts/2/6KxNMsvcN2vdVjRAjclCcFjBxSDdLSulgD2bTa4Fb9OvjLAVhU01Y30e2eoFZ9AVQDeHGibLVisQNHFZlZK0ic6Xr5sK1Jmm50uPDVUE7J1tA+0G25KxavH6dxDUZ/Ict+TvQfZMFRO7hnVZgAnRvqrYd3UfDt0BHZj/ZJobTwgK0Is8Dv996wpj17SWtVzQk9okIsTmqQRD4mO90222I0mlu8kmTfp7edbAy4ZJOStI9m4KBJcD0YGUJrH3XUC27YXLBlThYn9pdYXrSZiAdGnOdtKJeXQydyiAnCDDTJx+EmlsQpOgRUt7ytDKVE3huonvGVyeOCQ3WepGRhhBuBCBLReH2Md1Si5D7F2xCX+4q+m4ES9kYoaK62o1nwhZD+/JkjqgkgYS3z+6+QbY8fa6uITihnwsFZP+yFLPVrKoCxiI4E1LO2AVTEflWPgRFnTFGxRYjrKVd/cT4hZB5GLu/DVlw4fMTYcJS7+Ylv9b89SMQkEP+2zppzLIH4H+011gA4L4nN0xyCvstT0xNFS8xO8J3+EG0mx7wx/uCopOZjPc67lCbl8Pfno+UWUXMkUxo4paDPIb32C0Eoz/fKuGdWNMdznii0jBi9LGQe/8slEBUHGBuM/KN54qhZKHgS0Sd9bBOTI/8FKQyAdK1vQiRt8org=
  file: build/cloudwatch-log-destination$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: bhavikkumar/cloudwatch-log-destination
    tags: true
    go: 1.12.x