language: go
go:
- 1.12.x
- tip
env:
  global:
  - GO111MODULE=on GOOS=linux GOARCH=amd64
  - TF_IN_AUTOMATION=1
  - VERSION="0.11.13"
  - AWS_DEFAULT_REGION=us-east-1
  - secure: CpqEazNBgah8R94o4W+E0nQW3K4m9U0nGdpwqxl2464SNMZ9OBpvQ2ycR+smjENWij6pskgkHG1wHeL8kpBXr4AOrQiQMPZe89hRCUAulg3dwFVHbfvUZHistSv8iA/eHcbI2gZGEoR721MHEYQu2Em9zSFYS/ZMMWA5kCYgihqHSljpEhINzbGg46gs3ZJ31GmKhfmt0aUhmZU/1z0l9ba/k/lBFjjbnKWQmAwqTdlQqg3LWYOF6i6kW93wVUZuZBnoTWBaMF+410krpUKy9AnV/Y3lE8SIKA4W8UvLV15amZYGLfCfqERS6co1SIXb0XrXIDcQKZ9bM2xRpLJO7lzfYkYY52/wGxveioZVGmJdKBrZwFCEZe/TUkZQKAQfIpArPkHs5Ybk3GzS+VADBpcqLbs6jI4Y5xRBeF7RIBKDaewvs1eUp41dhnnrZJEOu921hYB0VCdgJD874PeGtJcn6KptHMJKSgHekllaWeox1uY0nNsduknX1bUmbeX7UhNheXQuFYtBogT8guPdlnJaxrn9BNvClTHA9iW8fsAQEuOp4R6LhUuLmMHS9xV9A2JyRMb9aQ3XQbEBRr2D4AnVijL+O9Dy2nJmZtCbiJk+q38wZiFDKauqYtfMxdEeh2cCPh88Ga+YnpR9qMDt/Jke0P2H2mshZwNKhsTZ+k4=
  - secure: j66iYu7QSYPXJu8B9rDKwaa8rcCE1g8XbUNaogfKj7AnWR3toXjrkNSp1S4C1jLC2IYX+wcXt7p0FR6ZuwYcWT+mWTj8QBoRfubARzFQ6vL6G8qDe/crbyG7QtGYHs5FP0gGov00lgFE5oHcYDW17021XGBCOXJ2nrzcilY8ksOcqI4+Y0mhU543+V4pnNGZJTP+173X8UvYhYeoT+1ZhGovhKjSRD93h0QLxKFWkrhDT8f467gW7p1Epqtj2RgkzFlfuiK6JGJeCDr5S3MxPvAfbw8X/JKDsfBUMMYZN2Nr34DEh7KaKT3u8A+FBHXqKvL3QyxImvxy9fRaihYENZrk1jy235jrAYELNdjWDQcz89aO6/e5eJy/BGAGxPhv3dngdCTpqlsRWOmz9R1IY+fIh1s59zqM2AAURFsLaBp125wn90tPxK9w4QGF6PZP0fPwsSDcBVz+fJ48+yFdQnaEsG8WOGTHdCRsl1uF8aNJIgdW+4my5Ca+8sRJM0Sj3t3mpYU4C+7eQ8dLAQ+uPmrlE++fcKLsEe03SIiog9CXxoFg1f+53jvup+JcqbwxLu7GbIde/HfhnVBj4GQjTgxm+KRM+8BYVhfwrvZQXwTZ82SMnGpKJXU01FQ9NG63G2zdd/61PeaIN1Dc3LmEH+MhYwgNAgBYtoRk0cFglkY=
  - secure: owqsBKuP6DeWd5mH+I7O6UhauifL4Fe2KEL/o7Du94+06jMTGNZiSI3qrtLtmk3KAi5VvG0oytXZk/hQIPcc6csjSW+8lLQDcIyGMZkQ9yxhLwTyNsXOhImoBKw3uojYsiwygn60XzZfplbakBd5LX3vzjaCogxg5EZShT2X8e3GoZSTR4t3TE8ycBv18hRGBz0PN+W1AJJJ9cY+W90I+YvhhHek7tb8OiM7WkyCr/jWb/dzPu6tp0zKx4ti32xx+4SLXD2l5P0ThkxGIaIbkhvxsCe/cS1HrP1MEFPZDfJZalGSkMfKr/EUXzbEfIRQOA2xirmxenlQ61hvaT6+ZgI7N/2L+gAGI7PdAMwqOoTmVq8UosIH6bhJ77flfaYph3RGOCRblhwEkSih4NLycGzKRU+/tI8vDYk8L4yQCK6yP8Hjz4ylL9moiKDHqD7TA1XiOatjzIOmm+E2l7Gp3CghGi7Txg5wUAkBlLiVjquxaAZ7LI7pFcFp0JlppUBUbvYiFN6mmKL6uS9AUlmn13o7IEwOJokXCKXno/NfWD/ba4PrO9RLWTGXABNpPhygftmSIy8eKOudJAzxElLK/P67bcXatEi2RBtbIn/ImGdZt70KOE3kNMhB/LhFe4WQZJtZTZF7cVWTjWc0loBjoei22KhG2iZxZvd95q4JxHc=
  - secure: LKH7mGR/71rsxixiL7IkuDJ6KzMEMb6SgtOdxjOiEteYxoTflfstSDglp0ib9thFQyIIQxNI8KMo+rfY26SdBDFrVD2p5nWxV0YF53nwurFZeKCW0+Xc5ahduD6g0sFn5raOn9nxPnWgfksMilDCAWExAslW/X3mfhfm8lECc+v05FOmJNFve8ySPTK+zdtZek4ichHs3ZDBQiV4F4HRhccJugi5w/eFLM/3D7uDgTGHcMpvOa2tbSXBEItr0ClhzxPc+1M2bBDqXtk/liHwxKHtApP8F1Uh4D5zgLU1E2UP8b1e1IXQRELNypPHwEy0HUgYALPWQhoUuGFPFF41wWkz4PFvAFubDQrO4BwH6scOC/51dMUlnp0hSGAAQTDECSSgFEQwdDFHh3QB/hd1uPGBCt501Z2RgSzNmsGAeXUi4OEyw+2r80Op0cEnfy1U9pe/GtvFdD9r+ksT8PH/qbWfA/vIJ2GB1zwnRt/s91vHILZIRQIBmV1aKZVo0xE3u4dO7Zq20zMmpLRX8wneTWTzgi+vpg8YiKB9MF0NN0eOxpBG28tEDgDWOLSaduhxH6bwo2Prf3panI16A+utpkCkmMn3z9tSoZVs02Neisr4OGGFd80tX+zd1xr4ocJ1V4L5AxQRd/uw+tn6efXs5FiD2LM2oNoBcY5fkbkVO8I=
  - secure: vBOjl3E0iXP+8NEtXTg7k9YWwuic9yKuDUIboSxZ8q7UEU4q/QM+QCD/Gl/RMUeZDAGJNbuhSDbheQwiDwbHAgxcuqwW3N8OksSRf6Y/9O8Ei1LyE6nEOlKeO9cNIlGABR0lQ+pY5dSNPOPzMY66yxJKxcZ2/iCsAlch59k/WQR7s6toGjGrpaA88KOkH5GMUXRj2FhY8BVeMuyB0Xb7MtUr6GJB4A+wrk27fJC1zGKZJhsKK3ojJ3I9vqC+CwXI1bkLq+L+jwGb5sEcqnpxbSsVbfceXTXwR3NhZjKm+l8L+zagG43+ecbRFLfIXZXreNojKnGe4qwG5aVPkcDAbFwAalUHKepOUI2ZWgBc3CcRQ8xOX7SEoaMksh0AZciIwEVUzvdkf47YJ61VKCpXKwDgs4V2wjKacspFH5z+0qDEQ14KRREXJc23w0/YKdF6OezEWhu0eG2Ht1X6+CTg1LXKgEbboAW0GtVi0BLjbFRYQU6yKQUjImGfFNmjIm3lfxy7lG2pYL9Xz/q5ANSC2wZL8VLQqPJ4MVFcK8B3scYlzxLajOXQZzGMztp+v0gfyDUkDEcOlIIcRKV2OWbuyCo1v9GBq3q/pirXC22Lzd14h4H0x2CXEmO2B/dThl4qHTrUbMXa12aXL9R+WKKjvmdO1dpxbejr5k2cP+Ra/Cc=
  - secure: YhpmG+OpjWFdJEdu/6XRi1K6MdNhXKfCeJZq3hTWaYX7lf5Fp+UByGuV55VbU+HTRR3HcHUNxWOyK5sahDLGjfjqffFA70cwaUtNYYolghh9thW8Gfus0o2asPeLBl66jdAcO4svU8k/e9wyNjMCmwlj8BgAGcFPtpR0qVSEGOrNCGNSu4z8m1KtDq25t/M6EJZV+m4z/dwkaAVyf7SMGlrNrF1xpFZPmAq1V5Hc+mfUgACTJ9UZ201+WDwCNRJgP47wMqriGd2lNGJ2ZHZ9ZFPhfa3xoEq7oa9MENhdgQj1fg+ZdE4XOX63B1b3i7gSwCuq04tTyZz3JJKDG7bBf1uqdY3DEijcgDc/kXoi4/WuFak9nXNCRDzJL4rlL2uuh4CTpTqou4m3Iv5K9zB/In0iOrxxlI21ZpWcQXY3yCihEUNKrZYxo3EukI5zI7OLsn97B1yOusarVlQdaHGSWLbQuyJr4ejlUEtj8DY9qm7rzSTrr5jVQHAzPKCcL1aLFfaydD/T1JAq/1yLOCMjeoAyKcNNs8mfKmN6RyW3dBCrafTNubnLYuwXsGIjd80/4CX58UXwdSDMoM021eI1loJT2scygJoRlzFRkBf9/qNny1j7I6Ts924Xj5AkdGC9lLqU0fHyUQW+bhdleyvqjVbSFD9ixFRiJ5kwHK3IuMU=
matrix:
  allow_failures:
  - go: tip
  fast_finish: true
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: bhavikkumar-github
    token:
      secure: c5v4OvSRZ7D5z00vE03z/ZvmB7jgf0GZUdRs7C4YZdW1CgxtQkg7pOdIxNO2P01n+awxXFQLgdNQYiLtoJzmGFDVdq+Jdxfp5eplnXMN3M8PC3TwuvZJRdQU3w6ar0dW2sfJAgq3WgCPbfN/9S27vsZaYUSsREox6mVJi4PiKUw4U2P767w8SolpfE6NV3MUnbzdLAtVgV5nn/4Q22T5BAEp6bM6gvPfJdPhfCYqKFysTf/ViZiWP5jfud2rbmmn+Ply7uZ5auoyj2t/nAQiK1uIr8qzvk7A2PRw5HggEgSGMIjTqGzG5ie0tSMr9INdAEUsVNDuVdGNq2/yUR+FQVDyJqbsPIhhwDIiUDncgXPZ/3F7e+2ySqbSR7ljfhjroIjj62Gwq8lBZvQYjURvZUmR6Td0YaHWo1mXg4eYOV39ndI1okYRpEForTbweZ+JVTE7IJQmRFJHiXW7BUXr1Joxd4KCvxtwxwhsqXqvg1fn8smtx5QI2d509HehnUA0BHMvzEXlBqPoT4l9H4AjCYJ38SjJIuzgQXfjeA98gICA5wPpfipG0RDSUgiQavPpst8AzhIUTlwTLehf7cd4NhvkDejOyPAZMNLi0yHhxEwoEU7kYU6fiyfBLvIv8FqkZSbakRDdXJlBPGKYl8OCvcR6YPIJ+gTTvLva0QGuORA=
deploy_lambda: &deploy_lambda
  provider: script
  script: ./terraform apply -backup="-" -input=false -auto-approve -var aws_default_region=${AWS_DEFAULT_REGION}
    -var lambda_version=${TRAVIS_TAG} -var account_id=${AWS_ACCOUNT_ID} -var operations_account_id=${OPERATIONS_ACCOUNT_ID}
    -var role_name=${ROLE_NAME} deployment >/dev/null
  skip_cleanup: true
  on:
    repo: bhavikkumar/cloudwatch-log-destination
    tags: true
    go: 1.12.x
deploy_lambda_stage: &deploy_lambda_stage
  script: skip
  before_deploy:
    - ./terraform init -backend-config="bucket=terraform.bhavik.io" -backend-config="region=${AWS_DEFAULT_REGION}"
      -backend-config="dynamodb_table=terraform-state" -backend-config="kms_key_id=${KMS_KEY_ID}"
      -backend-config="role_arn=${ROLE_ARN}" deployment >/dev/null
  deploy:
    <<: *deploy_lambda
before_install:
- wget https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip
- unzip -o terraform_${VERSION}_linux_amd64.zip
- chmod +x terraform
install:
- go mod download
- go build -ldflags="-s -w" -o main main.go
script:
- go vet ./... 2> govet-report.out
- go test ./... -coverprofile=coverage.out -json > report.json
- sonar-scanner
after_success:
- zip cloudwatch-log-destination$TRAVIS_TAG.zip main
jobs:
  include:
  - stage: GitHub Release
    if: tag IS present
    go: 1.12.x
    script: skip
    deploy:
      provider: releases
      api_key:
        secure: fiqhQ8z2ts/2/6KxNMsvcN2vdVjRAjclCcFjBxSDdLSulgD2bTa4Fb9OvjLAVhU01Y30e2eoFZ9AVQDeHGibLVisQNHFZlZK0ic6Xr5sK1Jmm50uPDVUE7J1tA+0G25KxavH6dxDUZ/Ict+TvQfZMFRO7hnVZgAnRvqrYd3UfDt0BHZj/ZJobTwgK0Is8Dv996wpj17SWtVzQk9okIsTmqQRD4mO90222I0mlu8kmTfp7edbAy4ZJOStI9m4KBJcD0YGUJrH3XUC27YXLBlThYn9pdYXrSZiAdGnOdtKJeXQydyiAnCDDTJx+EmlsQpOgRUt7ytDKVE3huonvGVyeOCQ3WepGRhhBuBCBLReH2Md1Si5D7F2xCX+4q+m4ES9kYoaK62o1nwhZD+/JkjqgkgYS3z+6+QbY8fa6uITihnwsFZP+yFLPVrKoCxiI4E1LO2AVTEflWPgRFnTFGxRYjrKVd/cT4hZB5GLu/DVlw4fMTYcJS7+Ylv9b89SMQkEP+2zppzLIH4H+011gA4L4nN0xyCvstT0xNFS8xO8J3+EG0mx7wx/uCopOZjPc67lCbl8Pfno+UWUXMkUxo4paDPIb32C0Eoz/fKuGdWNMdznii0jBi9LGQe/8slEBUHGBuM/KN54qhZKHgS0Sd9bBOTI/8FKQyAdK1vQiRt8org=
      file: cloudwatch-log-destination$TRAVIS_TAG.zip
      skip_cleanup: true
      on:
        repo: bhavikkumar/cloudwatch-log-destination
        tags: true
        go: 1.12.x
  - stage: Deploy to Development
    <<: *deploy_lambda_stage
    env:
    - TF_WORKSPACE=development
    - secure: JwkF+FReR42LjM/azgdNXKMeCa8Kd9LeaBAOyqtmmHXZRVCnskBv/q4cz9x9AueAso3eYRKgicUPg6a1wpcwAZ+LXQmjVKPPh9pXNzt47TsBpE/HCRgqWXLxl/mxMxHTqK67FGGEUeyTDoaQ7A+SyEfOJJstdJsty7OHNF7K3A8h7bb3FXDB2yfAy3fyAn6C5n+MkO3Wa9Ja3g3+ukdPJV45O4dJJ+RKfiHYUnrEaburmKqPmvGbFZxYo6yULSMf9K8sg1V0A2N+94+5R/kbnfoiPJrLAmKunzIlC+A2MtnQgfyiZxJZBHKw+mJoDNQY5TNks7YnViLB+dGsq2JxaHmeLxd5kKRcbB9LzZJ7g6WYQZ9Wt1kTYt3QShZKrz8rSH5vO9OYXclZiYJFuPVtLYm5gRR+EC11tX9V+KFF+MhhSC78ZF0/AhyNYJEhtXAGxnMeT1p1QBUA/A2phooy63UNUa2Y5Jy+AZrxSzNurIpd67NDBDiyJFg/LlUwHlfGWv8A6qqEIeos9NOVrmw/xKIwm9JhVQ50vL9kY7H6w/ICWT8ZFUrG1Zkuv30Ny8pTTrm/Ta9+fMbI2bpq5Duv56HuvaBl2q7NLF5pb3Osy5nPoxBhIl3fEuexKA7oXbzDdQcXfyXcwo9XIFccmscGXDNKjpdOnXLrp+If7z4LFWA=
    go: 1.12.x
    script: skip
    deploy:
      <<: *deploy_lambda
      on:
        all_branches: true
        go: 1.12.x